name: Delete GitHub Runner

on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: 'Name of the Resource Group'
        required: true
        default: 'SCC-SB-CORP-GIT-NETBOX'
      clusterName:
        description: 'AKS Cluster Name'
        required: true
        default: 'scc-sb-corp-git-netbox-ci-aks'
      runnerName:
        description: 'Runner Name to Delete'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  delete-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ github.event.inputs.resourceGroupName }} \
            --name ${{ github.event.inputs.clusterName }} \
            --admin

      - name: Delete GitHub Runner
        run: |
          kubectl delete pod ${{ github.event.inputs.runnerName }} -n github-runners
          
      - name: Verify Runner Deletion
        run: |
          echo "Verifying runner deletion..."
          if kubectl get pod ${{ github.event.inputs.runnerName }} -n github-runners 2>/dev/null; then
            echo "Error: Runner ${{ github.event.inputs.runnerName }} still exists"
            exit 1
          else
            echo "Runner ${{ github.event.inputs.runnerName }} successfully deleted"
          fi
